[package]
name = "trithemius"
version = "0.1.0"
authors = ["Jack Lund <jackl@geekheads.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
repl-rs = "0.2.3"
clap = "2.33.3"

[dependencies.tokio]
version = "0.2.22"
features = ["rt-threaded", "rt-core", "macros", "tcp", "io-util", "sync", "stream"]
